[theme]
base="dark"
primaryColor="#00FF00"
backgroundColor="#0E1117"
secondaryBackgroundColor="#161B22"
textColor="#E6EDF3"
[global]
disableWidgetStateDuplicationWarning = true
[server]
headless = true
enableCORS = false
enableXsrfProtection = false
[github]
token = "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"
